import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:getx_app/src/const.dart';
import 'package:getx_app/src/controllers/account_controller.dart';
import 'package:getx_app/src/items/components.dart';
import 'package:getx_app/src/pages/payment.dart';

class Account extends StatelessWidget {
  final Components components = Components();
  final AccountController accountController = Get.put(AccountController());

  

  @override
  Widget build(BuildContext context) {
    return Container(
      height: Get.mediaQuery.size.height * 0.85,
      width: double.infinity,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(15),
          topRight: Radius.circular(15),
        ),
        boxShadow: [BoxShadow(color: Colors.grey.withOpacity(.5), blurRadius: 8)],
      ),
      child: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: Constants.APP_HORIZONTAL_WIDTH),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              SizedBox(height: 15),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  GestureDetector(
                      onTap: () {
                        Get.back();
                      },
                      child: Icon(Icons.close)),
                  Text(
                    'account'.tr,
                    textScaleFactor: 1.4,
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  Text('faq'.tr, textScaleFactor: 1.5),
                ],
              ),
              SizedBox(height: 40),
              components.textWithWidget('uniting_meals'.tr,
                  fontSize: 8,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false,
                  subTitleText: 'change_your_account_information'.tr),
              SizedBox(height: 5),
              components.myDivider(),
              SizedBox(height: 5),
              components.textWithWidget('payment'.tr,
                  fontSize: 8,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false,
                  subTitleText: 'manage_payment_methods_and_door_dash_credits'.tr,onTapNavigateTo: Payment()),
              SizedBox(height: 5),
              components.myDivider(),
              SizedBox(height: 5),
              components.textWithWidget('addresses'.tr,
                  fontSize: 8,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false,
                  subTitleText: 'add_or_remove_a_delivery_address'.tr),
              SizedBox(height: 5),
              components.myDivider(),
              SizedBox(height: 5),
              components.textWithWidget('privacy'.tr,
                  fontSize: 8,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false,
                  subTitleText: 'manage_your_privacy_settings'.tr,
                  onTapNavigateTo: Payment()),
              SizedBox(height: 5),
              components.myDivider(),
              SizedBox(height: 5),
              components.textWithWidget('get'.tr + ' \$0 ' + 'delivery_fee_with_dash_pass'.tr,
                  fontSize: 8,
                  fontColor: Constants.APP_BLUE_COLOR,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 10),
              components.myDivider(),
              SizedBox(height: 10),
              components.textWithWidget('link_facebook'.tr,
                  fontSize: 8,
                  isBold: false,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 10),
              components.myDivider(),
              SizedBox(height: 10),
              components.textWithWidget('delivery_support'.tr,
                  fontSize: 8,
                  isBold: false,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 10),
              components.myDivider(),
              SizedBox(height: 10),
              components.textWithWidget('gift_card'.tr,
                  fontSize: 8,
                  isBold: false,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 5),
              components.myDivider(),
              SizedBox(height: 10),
              components.textWithWidget('refer_friends'.tr + ', ' + 'get'.tr + ' \$10.00',
                  fontColor: Constants.APP_COLOR,
                  fontSize: 8,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 55),
              components.textWithWidget('notifications'.tr,
                  isCapital: true, fontSize: 9, addPadding: false),
              SizedBox(height: 20),
              Obx(() => components.textWithSwitch('delivery_push_notifications'.tr,
                  fontSize: 18,
                  switchValue: accountController.deliveryPushNotificationsEnabled.value,
                  onChangedSwitch: accountController.changePushNotificationsValue)),
              components.myDivider(),
              Obx(() => components.textWithSwitch('delivery_sms_notifications'.tr,
                  fontSize: 18,
                  switchValue: accountController.deliverySMSNotificationsEnabled.value,
                  onChangedSwitch: accountController.changeDeliverySMSNotificationValue)),
              components.myDivider(),
              Obx(() => components.textWithSwitch('promotional_push_notifications'.tr,
                  fontSize: 18,
                  switchValue: accountController.promotionalPushNotificationsEnabled.value,
                  onChangedSwitch: accountController.changePromotionalPushNotificationsValue)),
              SizedBox(height: 45),
              components.textWithWidget('more'.tr, isCapital: true, fontSize: 9, addPadding: false),
              SizedBox(height: 30),
              components.textWithWidget('become_a_dasher'.tr,
                  fontSize: 8,
                  isBold: false,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 10),
              components.myDivider(),
              SizedBox(height: 10),
              components.textWithWidget('become_a_partner_restaurant'.tr,
                  fontSize: 8,
                  isBold: false,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 10),
              components.myDivider(),
              SizedBox(height: 10),
              components.textWithWidget('legal'.tr,
                  fontSize: 8,
                  isBold: false,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 10),
              components.myDivider(),
              SizedBox(height: 10),
              components.textWithWidget('logout'.tr,
                  fontSize: 8,
                  isBold: false,
                  addPadding: false,
                  iconData: Icons.keyboard_arrow_right,
                  inCircleAvatar: false),
              SizedBox(height: 10),
              components.myDivider(),
              SizedBox(height: 10),
            ],
          ),
        ),
      ),
    );
  }
}
